
import 'package:aegis247_admin_panel/res/strings/str_keys.dart';

Map<String, String> stringsEn = {
  StringKeys.appTitle: 'FinanceMe',
  StringKeys.signInTitle: 'Sign In',
  StringKeys.signInButton: 'Sign In',
  StringKeys.createAccount: 'Create Account',
  StringKeys.safetyText: 'SAFETY',
  StringKeys.safetyInfoText: 'Safety and Security for mobile staff',
  StringKeys.safetyIntroText1: 'Safety cover for you',
  StringKeys.safetyIntroText2: 'Privacy your way',
  StringKeys.safetyIntroText3: 'Alert others for help',
  StringKeys.safetyIntroText4: 'Respond to the unplanned',
  StringKeys.signUPTitle: 'FOR A SAFER YOU',
  StringKeys.signUPMessage: 'Create an Account',
  StringKeys.signUPMessage2: 'Already a Member? ',
  StringKeys.signUPMessage2Bold: 'Sign In',
  StringKeys.signUPCountrySearch: 'Search',
  StringKeys.signUPJoinTeam: 'JOIN THE TEAM',
  StringKeys.loginTitle: 'WELCOME BACK',
  StringKeys.loginMessage: 'Account Sign In',
  StringKeys.loginMessage2: 'Don\'t have an account?',
  StringKeys.loginMessage2Bold: ' Create Account',
  StringKeys.loginForgotPassword: 'Forgot Password?',
  StringKeys.callVerification: 'Cell Verification',
  StringKeys.enterSmsCode: 'Enter the SMS code sent to your Cell.',
  StringKeys.doNotReceiveCode: 'Didn\'t received the SMS? ',
  StringKeys.reSendCode: 'RESEND',
  StringKeys.verifySignUp: 'VERIFY & SIGN UP',
  StringKeys.signUPName: 'Name',
  StringKeys.signUPNameHint: 'Johnson Doe',
  StringKeys.signUPEmail: 'Email',
  StringKeys.signUPEmailHint: 'Johnsondoe@nomail.com',
  StringKeys.signUPPassword: 'Password',
  StringKeys.signUPPasswordInfo: '[Min 8 characters including 1 capital 1 symbol]',
  StringKeys.signUPPhNo: 'Phone No.',
  StringKeys.signUPTMMessage: 'You must accept the Terms of Service and Privacy Policy to create an account.',
  StringKeys.signUPSubmit: 'submit',
  StringKeys.signUpTermsCond1: 'I accept the ',
  StringKeys.signUpTermsCond2: 'Terms of Service',
  StringKeys.signUpTermsCond3: 'and',
  StringKeys.signUpTermsCond4: 'Privacy Policy',
  StringKeys.signInBody: 'Please enter your phone number, we will send a verification over that phone number.',
  StringKeys.phoneNumberHint: 'Phone number',
  StringKeys.confirmationCodeTitle: 'Confirmation code',
  StringKeys.confirmationCodeBody: 'Please enter the confirmation code sent over your phone number.',
  StringKeys.confirmationCodeHint: 'Confirmation code',
  StringKeys.createAccountTitle: 'Create Account',
  StringKeys.createAccountBody: 'Please sign up to continue',
  StringKeys.emptyUserNameError: 'Please enter your name.',
  StringKeys.invalidUserNameError: 'Name should not contain number or any special characters.',
  StringKeys.createAccountButton: 'Create Account',
  StringKeys.tncAccepted: 'By creating an account, I agree to the Terms of usage and Privacy Policy.',
  StringKeys.fullNameHint: 'Full name',
  StringKeys.safetyPlan: 'Safety Plan',
  StringKeys.location: 'Location',
  StringKeys.florida: 'Florida',
  StringKeys.safetyArea: 'Safety Area',
  StringKeys.personAtLocation: 'Person(s) at Location',
  StringKeys.timer: 'Timer',
  StringKeys.selectValidTimer: 'Please select valid start and end time.',
  StringKeys.contactsToNotify: 'Contacts to Notify',
  StringKeys.start: 'START',
  StringKeys.guidance: 'Guidance',
  StringKeys.guidanceonhowtopreventorrespondtotheunplanned: 'Guidance on how to prevent or respond to the\nunplanned.',
  StringKeys.forinformationpurposesonlyInanemergencycallemergencyservices:
      'For information purposes only\nIn an emergency call emergency services.',
  StringKeys.prevention: 'Prevention',
  StringKeys.response: 'Response',
  StringKeys.personalSafety: 'Personal Safety',
  StringKeys.vehicles: 'Vehicles',
  StringKeys.severWeather: 'Sever Weather',
  StringKeys.help: 'Help',
  StringKeys.helpFaq: 'Help FAQ',
  StringKeys.share: 'Share',
  StringKeys.accept: 'Accept',
  StringKeys.decline: 'Decline',
  StringKeys.settings: 'Settings',
  StringKeys.searchAddress: 'Search Address',
  StringKeys.moreAboutAddress: 'More about address',
  StringKeys.favorite: 'Favorite',
  StringKeys.setLocationOnMap: 'Set location on map',
  StringKeys.addFavouriteLocation: 'Add favorite Location',
  StringKeys.createYourSafetyPlanQuicker: 'Create your safety plan quicker.',
  StringKeys.newa: 'New',
  StringKeys.name: 'Name',
  StringKeys.search: 'Search',
  StringKeys.delete: 'Delete',
  StringKeys.account: 'Account',
  StringKeys.groups: 'Groups',
  StringKeys.notifications: 'Notifications',
  StringKeys.accuracy: 'Accuracy',
  StringKeys.contact: 'Contact',
  StringKeys.termsofService: 'Terms of Service',
  StringKeys.privacyPolicy: 'Privacy Policy',
  StringKeys.precise: 'Precise',
  StringKeys.update: 'Update',
  StringKeys.details: 'Details',
  StringKeys.email: 'Email',
  StringKeys.changePassword: 'Change Password',
  StringKeys.oldPassword: 'Old Password',
  StringKeys.newPassword: 'New Password',
  StringKeys.confirmPassword: 'Confirm Password',
  StringKeys.characters: 'characters',
  StringKeys.mobilePhoneUse: 'Mobile Phone Use',
  StringKeys.whatisaegis247: 'What is Aegis 24/7?',
  StringKeys.wasthisanswerhelpful: 'Was this answer helpful?',
  StringKeys.yes: 'Yes',
  StringKeys.no: 'No',
  StringKeys.tryagain: 'Try Again',
  StringKeys.whoops: 'Whoops!',
  StringKeys.connection:
      'It seems there is something wrong with\n your internet connection. Please check\n your connection.',
  StringKeys.changeNumber: 'Change Number',
  StringKeys.next: 'Next',
  StringKeys.cancel: 'Cancel',
  StringKeys.oldPhonenumber: 'Old Phone No.',
  StringKeys.newPhonenumber: 'New Phone No.',
  StringKeys.personname: 'Person Name',
  StringKeys.add: 'Add',
  StringKeys.maxcharacters: 'Max 20 Characters',
  StringKeys.notifyContact: 'Notify Contacts',
  StringKeys.notifyContactHelpDetails:
      'Select people you want to notify if you need help.\nSelect at least one contact.',
  StringKeys.notifyContactCheckInOutDetails:
      'Be seen. Notify on Check In/Out of a location.\nYour safety plan is also shared. Optional selection.',
  StringKeys.notifyContactErrorMsg: 'You must select at least one contact in Help.',
  StringKeys.checkinout: 'Check in/out',
  StringKeys.individuals: 'Individuals',
  StringKeys.group: 'Group',
  StringKeys.deletefavorite: 'Delete Favorite?',
  StringKeys.areyousuredeletefavorite: 'Are you sure want to delete this from your favorite list?',
  StringKeys.logout: 'Logout',
  StringKeys.areyousurelogout: 'Are you sure want to logout from the app?',
  StringKeys.deleteaccount: 'Delete Account',
  StringKeys.areyousuredeleteaccount:
      'Are you sure you want to delete your account?\n\n This will remove all your details and you will have to register again in order to use the app.',
  StringKeys.deletegroup: 'Delete group?',
  StringKeys.areyousuredeletegroup: 'Are you sure want to delete this group from the list?',
  StringKeys.activehelp: 'Active Help?',
  StringKeys.areyousureactivehelp: 'Are you sure want to active help?',
  StringKeys.active: 'Active',
  StringKeys.turnofnotifications: 'Turn Off Notifications?',
  StringKeys.notificationsareneededtohelpkeepyousafe: 'Notifications are needed to help keep you safe.',
  StringKeys.turnoff: 'Turn Off',
  StringKeys.ok: 'Ok',
  StringKeys.welldone: 'Well Done!',
  StringKeys.phonenumbersuccessfullyupdate:
      'Phone number successfully updated.\n\n Make sure when you Sign In that you use your new phone number.',
  StringKeys.locationsharedwithselectedcontacts: 'The location has been shared with selected contact(s).',
  StringKeys.successfullychangedyourpassword:
      'You successfully changed your password!\n\n You can now use your new password to Sign In your account',
  StringKeys.contactResponded: 'Contact replied',
  StringKeys.iamok: 'I am Okay',
  StringKeys.areYouOkay: 'you are okay',
  StringKeys.deletion: 'deletion',
  StringKeys.helpactivated: 'HELP ACTIVATED',
  StringKeys.ifemergencycallservice: 'IF EMERGENCY CALL EMERGENCY SERVICES.',
  StringKeys.helpsmsnotificationsenttocontactlistedsafetyplan:
      'Help SMS notifications have been sent to Contact(s) listed in your safety plan.',
  StringKeys.send: 'Send',
  StringKeys.startingSoon: 'Starting soon',
  StringKeys.hours: 'HOURS',
  StringKeys.mins: 'MINUTES',
  StringKeys.quickaddtenmins: 'Quick add\n10 mins',
  StringKeys.youaresharingyourlivelocationwithcontacts: 'You are sharing your live location with contacts.',
  StringKeys.stopsharinganytimeandtheywillbenotified:
      'Selected contact(s) notified if you stop sharing and when you arrive.',
  StringKeys.stopLiveSharing: 'Stop Live Sharing',
  StringKeys.selectpreferredunit: 'Select preferred unit',
  StringKeys.preciselocationneededwhenyouactivehelp: 'Precise location needed when you active help',
  StringKeys.meter: 'Meter',
  StringKeys.feet: 'Feet',
  StringKeys.pinnedLocation: 'Pinned Location',
  StringKeys.moreaboutaddress: 'More about address',
  StringKeys.tellusyourquestion: 'Tell us your question',
  StringKeys.units: 'Units',
  StringKeys.distance: 'Distance',
  StringKeys.language: 'Language',
  StringKeys.sharewithloveones: 'Share Aegis 24/7 with others',
  StringKeys.maketheirpersonalsafetysimple: 'Make their personal safety simple',
  StringKeys.appversion: 'App version',
  StringKeys.static: 'Static',
  StringKeys.destination: 'Destination',
  StringKeys.addnewgroup: 'Add New Group',
  StringKeys.addgroup: 'Add Group',
  StringKeys.editGroup: 'Edit Group',
  StringKeys.viewGroup: 'View Group',
  StringKeys.deleteGroup: 'Delete Group',
  StringKeys.resetithere: 'Reset It Here',
  StringKeys.gobackto: 'Go back to ',
  StringKeys.sendLink: 'Send link',
  StringKeys.forgotpasswordText: "Enter the cell number linked to your account. An SMS to reset will be sent.",
  StringKeys.resetpasswordText: "Enter a new password for your account.",
  StringKeys.resetpassword: "RESET PASSWORD",
  StringKeys.searchTopic: 'Search Topic',
  StringKeys.save: 'Save',
  StringKeys.errorOccured: 'Error Occurred!',
  StringKeys.verify: 'Verify',
  StringKeys.sameNumberError: 'You have entered same numbers,Please use different numbers',
  StringKeys.codeSent: 'Code has been sent',
  StringKeys.safetyPlanActive: 'Safety plan is active',
  StringKeys.safetyPlanReached: 'You have arrived at your location',
  StringKeys.safetyPlanExit: 'User is Exit from Location',
  StringKeys.satelliteView: 'Satellite View',
  StringKeys.streetView: 'Street View',
  StringKeys.basicView: 'Basic View',
  StringKeys.shouldHaveSamePassword: 'New password and confirm password are not same',
  StringKeys.shouldNotHaveSamePassword: 'New password and old password are same',
  StringKeys.emptyFields: 'Please enter password at empty fields',
  StringKeys.successForChangePassword:
      'You successfully changed your password!\n You can now use your new password to Sign In to your account!',
  StringKeys.locationSharing: 'Location Sharing',
  StringKeys.sharewithuptotwootherpeople: 'Share with up to two other people.',
  StringKeys.selectContactsDetail: 'Select those contacts you want to share the location with.',
  StringKeys.successForChangePassword:
      'You successfully changed your password!\n You can now use your new password to Sign In to your account!',
  StringKeys.locationAccuracyDialogTitle: 'Location Accuracy',
  StringKeys.locationAccuracyDialogDec: 'Select the accuracy when you share\nyour location. Precise recommended.',
  StringKeys.locationApproximate: 'Approximate',
  StringKeys.selectContactsDetail: 'Select those contacts you want to share the location with.',
  StringKeys.back: 'Back',
  StringKeys.activeHelp: 'Activate Help?',
  StringKeys.activeHelpBody: 'Are you sure want to active help?',
  StringKeys.activeHelpButton: 'Active',
  StringKeys.confirm: 'Confirm',
  StringKeys.favourites: 'Favorites',
  StringKeys.areaAndLandmark: 'Area, Landmark',
  StringKeys.deleteFavorite: 'Are you sure you want to delete this from your favorites list?',
  StringKeys.emptyLocationAddress: 'Please enter Search Address.',
  StringKeys.noRecentLocations: 'No Recent locations',
  StringKeys.deleteFavorite: 'Are you sure you want to delete this from your favorites list?',
  StringKeys.emptyLocationName: 'Please enter location name.',
  StringKeys.noRecentLocations: 'No recent locations',
  StringKeys.favoriteLocations: 'Favorite locations',
  StringKeys.selectContacts: 'Select Contacts',
  StringKeys.selectHelpDetail:
      'Select contacts to alert for help.\n\nContacts will receive a message for help, see your live location, name and cell details.',
  StringKeys.viewDetails: 'View details',
  StringKeys.complete: 'Complete',
  StringKeys.edit: 'Edit',
  StringKeys.editPlanDescription: 'Edit your plan.',
  StringKeys.completePlanDescription: 'You are at a location but want to complete.',
  StringKeys.cancelPlanDescription: 'If you have not arrived at the location.',
  StringKeys.viewPlanDescription: 'See the details of your plan.',
  StringKeys.staticLocations: 'Static Location',
  StringKeys.selectPeopleYouWantToShareaLocationWith: 'Select people you want to share a location with.',
  StringKeys.onlythelocationyouselectwillbeshared: 'Only the location you select will be shared.',
  StringKeys.earlyCheckoutNotificationBody: 'Early exit from safety area.',
  StringKeys.autoHelpText1: 'Safety plan expired',
  StringKeys.autoHelpText2: 'Time for action',
  StringKeys.autoHelpText3: 'Respond now',
  StringKeys.messagePanelText1: 'Starting soon',
  StringKeys.messagePanelText2: 'Non arrival',
  StringKeys.messagePanelText3: 'Active plan',
  StringKeys.messagePanelText4: 'Expired plan',
  StringKeys.messagePanelText5: 'Early plan start',
  StringKeys.autoHelpDescriptionText1:
      '\nComplete and monitoring stops.\nContinue and extend timer.\nLeave the safety area.\n\nHelp alert sent in 6 mins if no response.',
  StringKeys.autoHelpDescriptionText2:
      '\nComplete and monitoring stops.\nContinue and extend timer.\nLeave the safety area.\n\nNo response and help alert sent.',
  StringKeys.autoHelpDescriptionText3:
      '\nComplete and monitoring stops.\nContinue and extend timer.\nLeave the safety area.\n\nHelp alert will activate if no response.',
  StringKeys.seconds: 'SECONDS',
  StringKeys.allow: 'Allow'
};
